services:
  wordpress:
    container_name: security-wp
    image: wordpress:6.6-apache
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./data/wordpress/:/var/www/html/
      - ./src/simple-security.php:/var/www/html/wp-content/plugins/simple-wordpress-security/simple-wordpress-security.php
    environment:
      WP_HOME: "http://localhost:8080"
      WP_SITEURL: "http://localhost:8080"
      WORDPRESS_DB_NAME: "root"
      WORDPRESS_DB_HOST: "db"
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DB_PASSWORD: "root"
      DISABLE_HTTPS: 1
    healthcheck:
      test: ["CMD", "curl" ,"-I", "http://localhost:8080"]
      timeout: 20s
      retries: 10
    networks:
      - security
  db:
    container_name: security-db
    image: mariadb:11.3
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - security

  e2e:
    image: cypress
    build: ./e2e
    container_name: security-cypress
    depends_on:
      - db
      - wordpress
    environment:
      - CYPRESS_baseUrl=http://web
    command: npx cypress run
    volumes:
      - ./e2e/cypress:/app/cypress
      - ./e2e/cypress.config.js:/app/cypress.config.js
    networks:
      - security

networks:
  security:
    driver: bridge

volumes:
  wordpress:
