name: Package Simple Security Plugin
on:
  push:
    tags:
      - '*'

jobs:
  web:
    name: "SimpleSecurityPlugin Plugin"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout 🛎"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Release Name
        id: release
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: "Update version"
        run: |

      - name: "ZIP & Publish"
        run: |
          set -eaux
          sed -i "s/\$VERSION/${{ steps.release.outputs.tag }}/" src/simple-security.php 
          mkdir -p /tmp/simple-security-plugin/
          cp -R src /tmp/simple-security-plugin/
          (cd /tmp && zip -r /tmp/simple-security-plugin.zip simple-security-plugin/)

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: /tmp/simple-security-plugin.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
